KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demod_ext/demodcomm/
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demod_ext/CXD2878Family_refcode/
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demod_ext/CXD2878Family_refcode/lib
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demod_ext/CXD2878Family_refcode/isdb_sat/

CXD2878Family_refcode_isdbs-objs := sony_demod_isdbs.o \
                                    sony_demod_isdbs3.o \
                                    sony_demod_isdbs_monitor.o \
                                    sony_demod_isdbs3_monitor.o \
					
obj-y += CXD2878Family_refcode_isdbs.o
