#ifndef __RTK_8168_DEF_H__
#define __RTK_8168_DEF_H__
#include <rbus/stb_reg.h>
#include <rbus/emcu_reg.h>
#include "sw_def_reg.h"
#define RTL_NETIF_FEATURES	(NETIF_F_RXCSUM | NETIF_F_HW_VLAN_CTAG_TX | NETIF_F_HW_VLAN_CTAG_RX | NETIF_F_TSO | NETIF_F_SG |NETIF_F_IP_CSUM)
#define RTL_TP_FEATURE			4
#define ETH_WAKE_DUMMY_REG STB_SW_DATA2_reg
#define ETH_VCPU_MDNS_OFFLOAD_BUFFER_START_ADDR 0x174000
#define CONFIG_SUPPORT_HW_MDNS_OFFLOADING_FUNCTION
#define EMCU_ST_IP_reg EMCU_ST_IP_EX4_7_reg
#define RTL_USE_NEW_CRC_WAKE_UP_METHOD 
#define CRC_PATTERN_WOL_MASK_SELECTION_REG 0xC130
#define CRC_PATTERN_WOL_MASK_REG 0x7C00
#define CRC_PATTERN_WOL_CRC1_REG 0xC020
#define CRC_PATTERN_WOL_CRC2_REG 0xC100
#define CRC_PATTERN_PACKET_START_REG 0x6A00
#define CRC_PATTERN_PACKET_PATTREN_REG 0x6A02
#endif