KBUILD_CPPFLAGS += -I$(srctree)/drivers/rtk_kdriver/etn/$(CHIP_NAME)/
KBUILD_CPPFLAGS += -I$(srctree)/drivers/rtk_kdriver/etn/
obj-$(CONFIG_RTK_KDRV_R8168) += rtk-8168.o 
rtk-8168-y := rtk_8168.o rtk_8168_mdns_offload.o $(CHIP_NAME)/rtk_8168_mdns_offload_fw.o

