KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demodcomm
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demod_ext/CXD2878Family_refcode/Source

CXD2878Family_refcode_i2c-objs := sony_i2c.o \
					
obj-y += CXD2878Family_refcode_i2c.o 



