#ifndef __RTK_USB_WIFI_H__
#define __RTK_USB_WIFI_H__

#define EHCI_PORT_Z0_TUNING_DATA_EFFECTED
#define EHCI_PORT_Z0_TUNING_ARRAY   {0x17, 0x19 ,0x1b}
#define EHCI_PORT_Z0_PAGE  0
#define EHCI_PORT_Z0_REG 0xe0
#define EHCI_PORT_Z0_BIT_OFFSET 0x1
#define EHCI_PORT_Z0_BIT_NUM 5
//#define EHCI_PORT_Z0_MASTER_PORT    2


#define  XHCI_PORT_Z0_TUNING_DATA_EFFECTED
#define XHCI_PORT_Z0_TUNING_ARRAY   {0x17, 0x19 ,0x1b}
#define XHCI_PORT_Z0_PAGE  0
#define XHCI_PORT_Z0_REG 0xe0
#define XHCI_PORT_Z0_BIT_OFFSET 0x1
#define XHCI_PORT_Z0_BIT_NUM 5
#endif

