/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCBASEDS_DATA_H_RPCGEN
#define _RPCBASEDS_DATA_H_RPCGEN

#include <rpc_common.h>

typedef rpc_s32_t HRESULT;

struct RPCRES_LONG {
	HRESULT result;
	rpc_s32_t data;
};
typedef struct RPCRES_LONG RPCRES_LONG;

struct USB_DEVICE_CONFIG_INFO {
	HRESULT ret;
	rpc_s32_t usb_ai_samplerate;
	rpc_s32_t usb_ai_format;
	rpc_s32_t usb_ai_chnum;
};
typedef struct USB_DEVICE_CONFIG_INFO USB_DEVICE_CONFIG_INFO;

struct RPC_CONNECTION {
	rpc_s32_t srcInstanceID;
	rpc_s32_t srcPinID;
	rpc_s32_t desInstanceID;
	rpc_s32_t desPinID;
	rpc_s32_t mediaType;
};
typedef struct RPC_CONNECTION RPC_CONNECTION;

struct RPC_SEND_LONG {
	rpc_s32_t instanceID;
	rpc_s32_t pinID;
	rpc_s32_t data;
};
typedef struct RPC_SEND_LONG RPC_SEND_LONG;

#endif /* !_RPCBASEDS_DATA_H_RPCGEN */
