#ifndef __RTK_MODULE_AUDIO_AO_H__
#define __RTK_MODULE_AUDIO_AO_H__
/*
######################################################################################
# AO EVENT DEFINE
######################################################################################
*/
typedef enum
{
    AUDIO_AO_EVENT_BT_MIC_INPUT_RP_EVENT_ID,
    AUDIO_AO_EVENT_BT_MIC_INPUT_WP_EVENT_ID,
    AUDIO_AO_EVENT_BT_MIC_INPUT_BUF_LENGTH_EVENT_ID,
    AUDIO_AO_EVENT_BT_MIC_INPUT_BASE_EVENT_ID,
    AUDIO_AO_EVENT_BT_MIC_INPUT_DELAY_EVENT_ID,
    AUDIO_AO_EVENT_BT_MIC_INPUT_VALID_SIZE_EVENT_ID,
    AUDIO_AO_EVENT_BT_MIC_OUTPUT_DMA_RP_EVENT_ID,
    AUDIO_AO_EVENT_BT_MIC_OUTPUT_DMA_WP_EVENT_ID,
    AUDIO_AO_EVENT_BT_MIC_OUTPUT_DMA_BASE_EVENT_ID,
    AUDIO_AO_EVENT_BT_MIC_OUTPUT_DMA_BUF_LENGTH_EVENT_ID,
    AUDIO_AO_EVENT_BT_MIC_OUTPUT_DMA_VALID_SIZE_EVENT_ID,
    AUDIO_AO_EVENT_BT_MIC_OUTPUT_DMA_DELAY_EVENT_ID,
    AUDIO_AO_EVENT_BT_MIC_TOTAL_DELAY_EVENT_ID,
    AUDIO_AO_EVENT_MAX_MIC_DELAY_EVENT_ID,
    AUDIO_AO_EVENT_MAX_UPDATE_INPUT_WP_PERIOD_EVENT_ID,
    AUDIO_AO_EVENT_EVENT_MAX
}AUDIO_AO_EVENT_EVENT_ID;

/*
######################################################################################
# AO EVENT TYPE DEFINE
######################################################################################
*/
typedef enum
{
    AUDIO_AO_EVENT_TYPE_ID,
    AUDIO_AO_TYPE_MAX
}AUDIO_AO_TYPE_ID;

/*
######################################################################################
# AO EVENT MERGER DW1 DEFINE
######################################################################################
*/
#define   AUDIO_AO_DW1_Event_max_update_input_wp_period    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_MAX_UPDATE_INPUT_WP_PERIOD_EVENT_ID)
#define   AUDIO_AO_DW1_Event_max_mic_delay    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_MAX_MIC_DELAY_EVENT_ID)
#define   AUDIO_AO_DW1_Event_bt_mic_total_delay    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_BT_MIC_TOTAL_DELAY_EVENT_ID)
#define   AUDIO_AO_DW1_Event_bt_mic_output_dma_delay    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_BT_MIC_OUTPUT_DMA_DELAY_EVENT_ID)
#define   AUDIO_AO_DW1_Event_bt_mic_output_dma_valid_size    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_BT_MIC_OUTPUT_DMA_VALID_SIZE_EVENT_ID)
#define   AUDIO_AO_DW1_Event_bt_mic_output_dma_buf_length    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_BT_MIC_OUTPUT_DMA_BUF_LENGTH_EVENT_ID)
#define   AUDIO_AO_DW1_Event_bt_mic_output_dma_base    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_BT_MIC_OUTPUT_DMA_BASE_EVENT_ID)
#define   AUDIO_AO_DW1_Event_bt_mic_output_dma_wp    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_BT_MIC_OUTPUT_DMA_WP_EVENT_ID)
#define   AUDIO_AO_DW1_Event_bt_mic_output_dma_rp    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_BT_MIC_OUTPUT_DMA_RP_EVENT_ID)
#define   AUDIO_AO_DW1_Event_bt_mic_input_valid_size    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_BT_MIC_INPUT_VALID_SIZE_EVENT_ID)
#define   AUDIO_AO_DW1_Event_bt_mic_input_delay    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_BT_MIC_INPUT_DELAY_EVENT_ID)
#define   AUDIO_AO_DW1_Event_bt_mic_input_base    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_BT_MIC_INPUT_BASE_EVENT_ID)
#define   AUDIO_AO_DW1_Event_bt_mic_input_buf_length    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_BT_MIC_INPUT_BUF_LENGTH_EVENT_ID)
#define   AUDIO_AO_DW1_Event_bt_mic_input_wp    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_BT_MIC_INPUT_WP_EVENT_ID)
#define   AUDIO_AO_DW1_Event_bt_mic_input_rp    MERGER_EVENT_DW1(EVENT_FW_AUDIO, AUDIO_AO_MODULE_ID, AUDIO_AO_EVENT_TYPE_ID, AUDIO_AO_EVENT_BT_MIC_INPUT_RP_EVENT_ID)

#define rtd_audio_ao_event_log(type, event, event_val, module_reserved)     rtd_audio_event_log(type, AUDIO_AO_MODULE_ID, event, event_val, module_reserved)
#endif /* __RTK_MODULE_AUDIO_AO_H__ */

