#
# Makefile for the linux kernel.
#

obj-$(CONFIG_MMC_RTKEMMC_PLUS)  := rtk_emmc.o
rtk_emmc-objs := rtkemmc_51.o rtkemmc_ioctl.o rtkemmc_pinmux.o cqhci-core.o

#obj-$(CONFIG_MMC_RTKEMMC_PLUS)  += rtkemmc_raw.o




