#KBUILD_CFLAGS += -Wall -Werror

obj-$(CONFIG_RTK_KDRV_DELIVERY) += realtek_delivery.o

realtek_delivery-objs := rtkdelivery_driver.o \
					rtkdelivery.o \
					rtkdelivery_debug.o \
					rtkdelivery_ioctl.o \
					rtkdelivery_ioctl_Delivery.o

