#ifndef __RTK_USB_WIFI_H__
#define __RTK_USB_WIFI_H__

#define EHCI_PORT_Z0_TUNING_DATA_EFFECTED
#define EHCI_PORT_Z0_TUNING_ARRAY   {0xc, 0xe, 0xf}
#define EHCI_PORT_Z0_PAGE  0
#define EHCI_PORT_Z0_REG 0xe0
#define EHCI_PORT_Z0_BIT_OFFSET 0x2
#define EHCI_PORT_Z0_BIT_NUM 4
#define EHCI_PORT_Z0_MASTER_PORT    2


#undef  XHCI_PORT_Z0_TUNING_DATA_EFFECTED
#define XHCI_PORT_Z0_TUNING_ARRAY   {0x0}
#define XHCI_PORT_Z0_PAGE  0
#define XHCI_PORT_Z0_REG 0xe0
#define XHCI_PORT_Z0_BIT_OFFSET 0x1
#define XHCI_PORT_Z0_BIT_NUM 5
#endif

