# Makefile for the Realtek scaler related drivers.
#
obj-y := scalerip.o scalermemory.o scaler_vgipdrv.o scaler_vodmadrv.o scaler_mcapdrv.o scaler_mdispdrv.o scaler_i3ddmadrv.o scaler_hdrdrv.o scaler_dtgdrv.o

