KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demodcomm
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demod_ext/CXD2878Family_refcode/

CXD2878Family_refcode_isdbt-objs := sony_demod_isdbt.o \
									sony_demod_isdbt_monitor.o \
					
obj-y += CXD2878Family_refcode_isdbt.o 
