#ifndef __RTK_8168_DEF_H__
#define __RTK_8168_DEF_H__
#include <rbus/stb_reg.h>
#include "sw_def_reg.h"
#define RTL_NETIF_FEATURES	(NETIF_F_RXCSUM | NETIF_F_HW_VLAN_CTAG_TX | NETIF_F_HW_VLAN_CTAG_RX)
#define RTL_TP_FEATURE			2
#define ETH_WAKE_DUMMY_REG STB_SW_DATA8_reg
#define ETH_VCPU_MDNS_OFFLOAD_BUFFER_START_ADDR 0x174000
#define CONFIG_SUPPORT_HW_MDNS_OFFLOADING_FUNCTION
#endif