KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demod_ext/demodcomm
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demod_ext/CXD2878Family_refcode
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demod_ext/CXD2878Family_refcode/lib

CXD2878Family_refcode_lib-objs := sony_math.o \
					
obj-y += CXD2878Family_refcode_lib.o 



