# Makefile for the Realtek scaler control drivers.
#
obj-y := scalercolorlib.o scalerthread_rtice2ap.o scalercolorlib_tv001.o scalercolorlib_IPQ.o scalercolorlib_tv010.o scalercolorlib_tv002.o scalercolor_engmenu.o

KBUILD_CFLAGS +=  -Werror

