obj-y		+= usb_cdc/
obj-y		+= usb_uac/
obj-y		+= usb_uvc/
obj-y		+= usb_hid/

obj-y		+= usb_buf_mgr.o
obj-y		+= usb_init.o
obj-y		+= usb_isr.o
obj-y		+= usb_mac.o
obj-y		+= usb_qevent_handler.o
obj-y		+= usb_utility.o
obj-y		+= usb_utility_2.o
