KBUILD_CPPFLAGS += -I$(srctree)/drivers/rtk_kdriver/wov/
KBUILD_CPPFLAGS += -I$(srctree)/drivers/rtk_kdriver/wov/include/
KBUILD_CPPFLAGS += -I$(srctree)/drivers/rtk_kdriver/wov/include/$(CHIP_NAME)/
KBUILD_CPPFLAGS += -I$(srctree)/drivers/rtk_kdriver/common/include/rbus

obj-$(CONFIG_RTK_WOV) += rtk-wov.o
rtk-wov-objs := rtk_wov.o