# Makefile for the Realtek I3DDMA drivers.
#
obj-y := dc2h_hsd.o dc2h2_hsd.o i3ddma.o i3ddmacolorfmtconvert.o i3ddma_drv.o i3ddma_hsd.o i3ddma_reg_array.o i3ddma2_hsd.o i4ddma_hsd.o i5ddma_hsd.o i6ddma_hsd.o hdmitx_hsd.o uvc_hsd.o
