KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demodcomm
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demod_ext/CXD2856Family_refcode/

CXD2856Family_refcode_isdbs-objs := sony_demod_isdbs.o \
                                    sony_demod_isdbs_monitor.o \
					
obj-y += CXD2856Family_refcode_isdbs.o
